### ISSUE TITLE
WebSocket connection to 'wss://switchboard.rtc.io/' failed: Error during WebSocket handshake: Unexpected response code: 404

### ISSUE THREAD

**Issue by yuvim86** [rtc-io/rtc-switchboard#26]
I was trying the video conferencing example which was given on the demo of rtc.io.
My local stream was working fine,but the remote user was not able to connect to me.
I was getting an error in console.

**WebSocket connection to 'wss://switchboard.rtc.io/' failed: Error during WebSocket handshake: Unexpected response code: 404**
I am on a https server.I think the rtc.io doesn't support https.

**Comment by silviapfeiffer** [comment]
switchboard is down right now - I'm trying to resurrect it

**Comment by silviapfeiffer** [comment]
Should work again.

**Comment by pacey** [comment]
Has this gone down again? Getting handshake timeouts :(
